spring.application.name=Auth

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.data.mongodb.uri=${MONGODB_URL}
jwt.secret.key=${JWT_SECRECT_KEY}
server.servlet.context-path=${SERVER_API}
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS}
spring.mail.protocol=${MAIL_PRO}
spring.mail.properties.mail.smtp.from=${SMTP_FROM}





